# Generated by Django 4.0.4 on 2022-05-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='categories',
            field=models.ManyToManyField(related_name='games', through='raterprojectapi.GameCategory', to='raterprojectapi.category'),
        ),
    ]
